apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-workload
data:
  cpuRequestMultiplier: 0.5
  memoryRequestMultiplier: 0.8
# imagePullSecrets: []string