apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-database
data:
  awsProvider: crossplane-aws
  dataKMSKey: data
  configKMSKey: config
  vpc: vpc
  subnetGroup: database
  esClusterSecretStore: external-secrets
# tags:
#   environment: dev