apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kafka-topic
spec:
  compositeTypeRef:
    apiVersion: kafka.entigo.com/v1alpha1
    kind: Topic
  mode: Pipeline
  pipeline:
  - step: queue-function
    functionRef:
      name: platform-apis-queue-fn
  - step: auto-ready
    functionRef:
      name: function-auto-ready
