---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: msk-observed
spec:
  compositeTypeRef:
    apiVersion: queue.entigo.com/v1alpha1
    kind: MSK
  mode: Pipeline
  pipeline:
  - step: queue-function
    functionRef:
      name: platform-apis-queue-fn
