apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkafkausers.kafka.entigo.com
spec:
  group: kafka.entigo.com
  names:
    kind: XKafkaUser
    plural: xkafkausers
  claimNames:
    kind: KafkaUser
    plural: kafkausers
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterName:
                  type: string
                namespace:
                  type: string
                consumerGroups:
                  type: array
                  items:
                    type: string

                providerConfigRef:
                  type: string
                  default: crossplane-aws
              required:
                - clusterName
