apiVersion: database.entigo.com/v1alpha1
kind: MariaDBUser
metadata:
  name: user-example
spec:
  name: user_example
  instanceRef:
    name: mariadb-example
  databaseRef:
    name: example-db
  privileges:
    - SELECT
    - INSERT
  grant:
    users:
      - example-user