{{- if .Values.bucket.install }}

apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: platform-apis-bucket
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  activate:
    - buckets.s3.aws.m.upbound.io
    - bucketpublicaccessblocks.s3.aws.m.upbound.io
    - bucketserversideencryptionconfigurations.s3.aws.m.upbound.io
    - bucketversionings.s3.aws.m.upbound.io
    - bucketownershipcontrols.s3.aws.m.upbound.io
    - users.iam.aws.m.upbound.io
    - policies.iam.aws.m.upbound.io
    - userpolicyattachments.iam.aws.m.upbound.io
    - accesskeys.iam.aws.m.upbound.io
    - secrets.secretsmanager.aws.m.upbound.io
    - secretversions.secretsmanager.aws.m.upbound.io

---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-apis-bucket
spec:
  package: {{ .Values.bucket.package.image }}:{{ .Values.bucket.package.tag }}
  skipDependencyResolution: true

{{- end }}

