{{- if .Values.postgresql.install }}
apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-database
data:
  awsProvider: {{ .Values.database.environmentConfig.awsProvider }}
  dataKMSKey: {{ .Values.database.environmentConfig.dataKMSKey }}
  configKMSKey: {{ .Values.database.environmentConfig.configKMSKey }}
  vpc: {{ .Values.database.environmentConfig.vpc }}
  subnetGroup: {{ .Values.database.environmentConfig.subnetGroup }}
  elasticacheSubnetGroup: {{ .Values.database.environmentConfig.elasticacheSubnetGroup }}
  {{- if .Values.database.environmentConfig.tags }}
  tags: {{- toYaml .Values.database.environmentConfig.tags | nindent 4 }}
  {{- else }}
  tags: {}
  {{- end }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  name: platform-apis-database-fn
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: tools
                        operator: In
                        values:
                          - 'true'
                  weight: 90
          containers: []
          tolerations:
            - effect: NoSchedule
              key: tools
              operator: Equal
              value: 'true'
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: platform-apis-database-fn
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: {{ .Values.database.function.image }}:{{ .Values.database.function.tag }}
  runtimeConfigRef:
    name: platform-apis-database-fn
{{- end }}
