{{- if (index .Values.functions "function-go-templating").install }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: {{ (index .Values.functions "function-go-templating").image }}:{{ (index .Values.functions "function-go-templating").tag }}
{{- end }}

{{- if (index .Values.functions "function-auto-ready").install }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: {{ (index .Values.functions "function-auto-ready").image }}:{{ (index .Values.functions "function-auto-ready").tag }}
{{- end }}

{{- range .Values.extraFunctions }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: {{ .image }}:{{ .tag }}
{{- end }}

{{- range .Values.extraProviders }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Provider
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: {{ .image }}:{{ .tag }}
{{- end }}
