{{- if .Values.queue.install }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  name: platform-apis-queue-fn
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8080"
            prometheus.io/path: "/metrics"
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: tools
                        operator: In
                        values:
                          - 'true'
                  weight: 90
          containers:
          - name: package-runtime
            resources:
              requests:
                cpu: 1m
                memory: 21Mi
              limits:
                cpu: 2000m
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
          securityContext:
            fsGroup: 2000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          tolerations:
            - effect: NoSchedule
              key: tools
              operator: Equal
              value: 'true'
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: platform-apis-queue-fn
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: {{ .Values.queue.function.image }}:{{ .Values.queue.function.tag }}
  runtimeConfigRef:
    name: platform-apis-queue-fn
{{- if eq .Values.queue.type "kafka" }}
---
apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-queue
data:
  awsProvider: {{ .Values.queue.kafka.environmentConfig.awsProvider }}
  {{- if .Values.queue.kafka.environmentConfig.tags }}
  tags: {{- toYaml .Values.queue.kafka.environmentConfig.tags | nindent 4 }}
  {{- else }}
  tags: {}
  {{- end }}
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: platform-apis-queue-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  activate:
    - clusters.kafka.aws.upbound.io
    - topics.topic.kafka.m.crossplane.io
    - topics.topic.kafka.crossplane.io
    - accesscontrollists.acl.kafka.m.crossplane.io
    - accesscontrollists.acl.kafka.crossplane.io
    - clusterproviderconfigs.kafka.m.crossplane.io
    - clusterproviderconfigusages.kafka.m.crossplane.io
    - secrets.secretsmanager.aws.m.upbound.io
    - secretversions.secretsmanager.aws.m.upbound.io
    - secretpolicies.secretsmanager.aws.m.upbound.io
    - singlescramsecretassociations.kafka.aws.m.upbound.io
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-apis-kafka
spec:
  package: {{ .Values.queue.kafka.package.image }}:{{ .Values.queue.kafka.package.tag }}
  skipDependencyResolution: true
{{- end }}
{{- end }}
