{{- if .Values.repository.install }}
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: platform-apis-repository
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  activate:
  - repositories.ecr.aws.m.upbound.io
  - lifecyclepolicies.ecr.aws.m.upbound.io
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-apis-repository
spec:
  package: {{ .Values.repository.package.image }}:{{ .Values.repository.package.tag }}
  skipDependencyResolution: true
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: platform-apis-repository
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ["artifact.entigo.com"]
        apiVersions: ["v1alpha1"]
        operations: ["DELETE"]
        resources: ["repositories"]
  validations:
    - expression: "!has(oldObject.spec.deletionProtection) || oldObject.spec.deletionProtection != true"
      message: "Repository is protected from deletion. Set spec.deletionProtection to false before deleting."
      reason: Forbidden
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: platform-apis-repository
spec:
  policyName: platform-apis-repository
  validationActions: [Deny]
  matchResources:
    namespaceSelector: {}
{{- end }}
