{{- if .Values.repository.install }}
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: platform-apis-repository
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  activate:
  - repositories.ecr.aws.m.upbound.io
---
apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-repository
data:
  awsProvider: {{ .Values.repository.environmentConfig.awsProvider }}
  awsRegion: {{ .Values.repository.environmentConfig.awsRegion }}
  dataKMSKey: {{ .Values.repository.environmentConfig.dataKMSKey }}
  scanOnPush: {{ .Values.repository.environmentConfig.scanOnPush }}
  imageTagMutability: {{ .Values.repository.environmentConfig.imageTagMutability }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  name: platform-apis-repository-fn
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: tools
                        operator: In
                        values:
                          - 'true'
                  weight: 90
          tolerations:
            - effect: NoSchedule
              key: tools
              operator: Equal
              value: 'true'
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: platform-apis-repository-fn
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: {{ .Values.repository.function.image }}:{{ .Values.repository.function.tag }}
  runtimeConfigRef:
    name: platform-apis-repository-fn
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-apis-repository
spec:
  package: {{ .Values.repository.package.image }}:{{ .Values.repository.package.tag }}
  skipDependencyResolution: true
{{- end }}
