{{- if .Values.zone.install }}
apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-tenancy
data:
  granularEgress: {{ .Values.tenancy.environmentConfig.granularEgress }}
  granularEgressExclude: {{ .Values.tenancy.environmentConfig.granularEgressExclude }}
  argoCDNamespace: {{ .Values.tenancy.environmentConfig.argoCDNamespace }}
  awsProvider: {{ .Values.tenancy.environmentConfig.awsProvider }}
  appProject:
    maintainerGroups: {{ .Values.tenancy.environmentConfig.appProject.maintainerGroups }}
    observerGroups: {{ .Values.tenancy.environmentConfig.appProject.observerGroups }}
  cluster: {{ .Values.tenancy.environmentConfig.cluster }}
  dataKMSAlias: {{ .Values.tenancy.environmentConfig.dataKMSAlias }}
  securityGroup: {{ .Values.tenancy.environmentConfig.securityGroup }}
  vpc: {{ .Values.tenancy.environmentConfig.vpc }}
  computeSubnetType: {{ .Values.tenancy.environmentConfig.computeSubnetType }}
  serviceSubnetType: {{ .Values.tenancy.environmentConfig.serviceSubnetType }}
  publicSubnetType: {{ .Values.tenancy.environmentConfig.publicSubnetType }}
  {{- if .Values.tenancy.environmentConfig.tags }}
  tags: {{- toYaml .Values.tenancy.environmentConfig.tags | nindent 4 }}
  {{- else }}
  tags: {}
  {{- end }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  name: platform-apis-tenancy-fn
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8080"
            prometheus.io/path: "/metrics"
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: tools
                        operator: In
                        values:
                          - 'true'
                  weight: 90
          containers:
          - name: package-runtime
            resources:
              requests:
                cpu: 1m
                memory: 12Mi
              limits:
                cpu: 2000m
                memory: 1024Mi
          tolerations:
            - effect: NoSchedule
              key: tools
              operator: Equal
              value: 'true'
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: platform-apis-tenancy-fn
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: {{ .Values.tenancy.function.image }}:{{ .Values.tenancy.function.tag }}
  runtimeConfigRef:
    name: platform-apis-tenancy-fn
{{- end }}
