{{- if .Values.zone.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-apis-zone
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["*"]
  - apiGroups: ["argoproj.io"]
    resources: ["appprojects"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "clusterroles"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["*"]
  - apiGroups: ["policies.kyverno.io"]
    resources: ["mutatingpolicies", "validatingpolicies"]
    verbs: ["*"]
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: zone-resource-dependencies
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  activate:
  - launchtemplates.ec2.aws.upbound.io
  - nodegroups.eks.aws.upbound.io
  - roles.iam.upbound.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-apis-zone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-apis-zone
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: crossplane-system
---
apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-zone
data:
  argoCDNamespace: {{ .Values.zone.environmentConfig.argoCDNamespace }}
  awsProvider: {{ .Values.zone.environmentConfig.awsProvider }}
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-apis-zone
spec:
  package: {{ .Values.zone.package.image }}:{{ .Values.zone.package.tag }}
  skipDependencyResolution: true
{{- end }}
