apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-queue
data:
  awsProvider: crossplane-aws
  configKMSKey: config
  kafkaNamespace: crossplane-kafka
