apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: repositories.artifact.entigo.com
spec:
  scope: Namespaced
  group: artifact.entigo.com
  names:
    kind: Repository
    plural: repositories
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "Name of the repository, defaults to the name of the resource if not specified"
                  x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                path:
                  type: string
                  description: "Prefix path for the repository"
                  x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
            status:
              type: object
              properties:
                repositoryUri:
                  type: string
                  description: "Repository URI for pulling and pushing images."
