apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: entigo-valkey-composition
  annotations:
    # Set the annotations defining the maintainer, source, license, and description of your Configuration
    meta.crossplane.io/maintainer: Taivo Pikkmets <taivo.pikkmets@entigo.com>
    meta.crossplane.io/source: github.com/entigolabs/platform-apis
    # Set the license of your Configuration
    meta.crossplane.io/license: AGPL
    meta.crossplane.io/description: |
      Manage Valkey instances through Kubernetes.
    meta.crossplane.io/readme: |
      ...
spec:
  crossplane:
    version: ">=v2.1.0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: ">=v0.11.0"
    - provider: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: ">=v0.11.6"
    - provider: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.9.1"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      version: ">=v2.2.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: ">=v2.2.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-eks
      version: ">=v2.2.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-secretsmanager
      version: ">=v2.2.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-kms
      version: ">=v2.2.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-elasticache
      version: ">=v2.2.0"
