hostname: docs.entigo.com
numberOfReplicas: 2
ingress:
  className: alb
  groupName: external
  scheme: internet-facing
container:
  image:
    repository: ghcr.io/entigolabs/entigo-docs
    tag: v0.0.0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeralStorage: "1Gi"
    limits:
      cpu: 200m
      memory: 256Mi
      ephemeralStorage: "2Gi"