apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3buckets.storage.entigo.com
spec:
  compositeTypeRef:
    apiVersion: storage.entigo.com/v1alpha1
    kind: S3Bucket
  mode: Pipeline
  pipeline:
    - step: s3bucket
      functionRef:
        name: platform-apis-storage-fn
