apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-zone
data:
  createAppsNamespace: true
  granularEgress: false
  granularEgressExclude: []
  granularNamespaceNetworkPolicy: false
  argoCDNamespace: "argocd"
  awsProvider: "crossplane-aws"
  appProject:
    maintainerGroups: []
    observerGroups: []
    sourceRepos: ["*"]
  cluster: eks
  dataKMSAlias: data
  securityGroup: "eks-node"
  vpc: vpc
  computeSubnetType: compute
  serviceSubnetType: service
  publicSubnetType: public
  controlSubnetType: control
  podSecurity: baseline
  roleMapping:
    - roleRef: maintainer
      groups: [ "maintainer" ]
    - roleRef: observer
      groups: [ "observer" ]
    - roleRef: contributor
      groups: [ "contributor" ]
  tags: {}