apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    crossplane.io/external-name: vpc
  name: vpc
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  initProvider: {}
  managementPolicies:
  - Observe
  providerConfigRef:
    kind: ClusterProviderConfig
    name: crossplane-aws
status:
  atProvider:
    arn: arn:aws:ec2:eu-north-1:111111111111:vpc/vpc-aaaaaaaaaaaaaaaaa
    assignGeneratedIpv6CidrBlock: false
    cidrBlock: 10.122.0.0/16
    defaultNetworkAclId: acl-0399fa955433ea583
    defaultRouteTableId: rtb-0c7434647e87b1e0e
    defaultSecurityGroupId: sg-007a53f64e7e4a7c4
    dhcpOptionsId: dopt-05ac0aa1e926a60f2
    enableDnsHostnames: true
    enableDnsSupport: true
    enableNetworkAddressUsageMetrics: false
    id: vpc-aaaaaaaaaaaaaaaaa
    instanceTenancy: default
    ipv6AssociationId: ""
    ipv6CidrBlock: ""
    ipv6CidrBlockNetworkBorderGroup: ""
    ipv6IpamPoolId: ""
    ipv6NetmaskLength: 0
    mainRouteTableId: rtb-0c7434647e87b1e0e
    ownerId: "111111111111"
    region: eu-north-1
  conditions:
    - lastTransitionTime: "2025-01-01T00:00:00Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2025-01-01T00:00:00Z"
      reason: Available
      status: "True"
      type: Ready

---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: eks
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  managementPolicies:
  - Observe
  providerConfigRef:
    kind: ClusterProviderConfig
    name: crossplane-aws
status:
  atProvider:
    version: "1.32"

---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Alias
metadata:
  name: data
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  initProvider: {}
  managementPolicies:
  - Observe
  providerConfigRef:
    kind: ClusterProviderConfig
    name: crossplane-aws
status:
  atProvider:
    arn: arn:aws:kms:eu-north-1:451773674263:alias/rein-net-kms/data
    id: alias/rein-net-kms/data
    region: eu-north-1
    targetKeyArn: arn:aws:kms:eu-north-1:451773674263:key/mrk-3a91cbba025546238ff6ba6a1f89ee12
    targetKeyId: mrk-3a91cbba025546238ff6ba6a1f89ee12

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: eks-node
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  initProvider: {}
  managementPolicies:
  - Observe
  providerConfigRef:
    kind: ClusterProviderConfig
    name: crossplane-aws
status:
  atProvider:
    arn: arn:aws:ec2:eu-north-1:451773674263:security-group/sg-00b54b0a78991d825
    description: EKS node shared security group

---
apiVersion: aws.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: crossplane-aws
spec:
  credentials:
    source: IRSA
status:
  users: 11

---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: crossplane-aws
spec:
  credentials:
    source: IRSA
status:
  users: 35