apiVersion: tenancy.entigo.com/v1alpha1
kind: Zone
metadata:
  annotations:
    example.com/role-group-reference: aaa-bbb-ccc-eee-rrr 
  name: myapp-zone-example
spec:
  namespaces:
    - name: myapp  # when no pool is explicitly specified, default pool is used. 
    - name: backend
      pool: spot
  pools: 
    - name: default
      limits:
        cpu: 10 # maximum number of CPU cores 
        memory: 100Gi
      requirements:
        - key: zone
          values:
            - eu-north-1a
            - eu-north-1b
        - key: arch
          values: 
            - amd64
            - arm64
        - key: instance-type
          values: 
            - t3.micro
        - key: capacity-type
          values: 
            - on-demand
    - name: spot
      limits:
        cpu: 10 # maximum number of CPU cores 
        memory: 100Gi
      requirements:
        - key: zone
          values:
            - eu-north-1a
            - eu-north-1b
        - key: arch
          values: 
            - amd64
            - arm64
        - key: instance-type
          values: 
            - t3.small
        - key: capacity-type
          values: 
            - spot
