apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: valkeyinstances.database.entigo.com
spec:
  compositeTypeRef:
    apiVersion: database.entigo.com/v1alpha1
    kind: ValkeyInstance
  mode: Pipeline
  pipeline:
    - step: valkeyinstance
      functionRef:
        name: platform-apis-database-fn
