CronJob: [Standard, Premium]

PostgreSQLInstance: [Standard, Premium]

PostgreSQLUser: [Enterprise]

PostgreSQLDatabase: [Enterprise]

Repository: [Standard, Premium]

WebAccess: [Basic, Standard, Premium]

WebApp: [Basic, Standard, Premium]

Zone: [Premium]

S3Bucket: [Basic, Standard, Premium]
