apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: entigo-docs
          image: ghcr.io/entigolabs/entigo-docs:v1.187
          ports:
            - containerPort: 80
              protocol: TCP