apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.numberOfReplicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: entigo-docs
          image: {{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            requests:
              cpu: {{ .Values.container.resources.requests.cpu }}
              memory: {{ .Values.container.resources.requests.memory }}
              ephemeral-storage: {{ .Values.container.resources.requests.ephemeralStorage }}
            limits:
              cpu: {{ .Values.container.resources.limits.cpu }}
              memory: {{ .Values.container.resources.limits.memory }}
              ephemeral-storage: {{ .Values.container.resources.limits.ephemeralStorage }}
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10