apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-zone
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["*"]
  - apiGroups: ["argoproj.io"]
    resources: ["appprojects"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-securityzone-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: security-zone
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: crossplane-system
