# In your Configuration package
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: zone-resource-dependencies
spec:
  activate:
  - launchtemplate.ec2.aws.m.upbound.io
  - nodegroup.eks.aws.m.upbound.io
  - role.iam.upbound.io
  
