---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: zones.tenancy.entigo.com
spec:
  compositeTypeRef:
    apiVersion: tenancy.entigo.com/v1alpha1
    kind: Zone
  mode: Pipeline
  pipeline:
    - step: zone
      functionRef:
        name: platform-apis-tenancy-fn
