apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresqldatabases.database.entigo.com
spec:
  compositeTypeRef:
    apiVersion: database.entigo.com/v1alpha1
    kind: PostgreSQLDatabase
  mode: Pipeline
  pipeline:
  - step: grant-owner-to-dbadmin
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
          kind: Grant
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: grant-owner-to-dbadmin
            name: {{ .observed.composite.resource.metadata.name }}-grant-owner-to-dbadmin
            namespace: {{ .observed.composite.resource.metadata.namespace }}
          spec:
            forProvider:
              role: "dbadmin"
              memberOf: "{{ .observed.composite.resource.spec.owner }}"
            providerConfigRef:
              kind: ProviderConfig
              name: {{ .observed.composite.resource.spec.instanceRef.name }}-providerconfig
  - step: database
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- $encoding := .observed.composite.resource.spec.encoding -}}
          {{- $lcCType := .observed.composite.resource.spec.lcCType -}}
          {{- $lcCollate := .observed.composite.resource.spec.lcCollate -}}
          {{- $template := .observed.composite.resource.spec.template -}}
          ---
          apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
          kind: Database
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: postgresql-database
            name: {{ .observed.composite.resource.metadata.name }}
            namespace: {{ .observed.composite.resource.metadata.namespace }}
          spec:
            forProvider:
              owner: {{ .observed.composite.resource.spec.owner }}
            {{- if $encoding }}
              encoding: {{ $encoding }}
            {{- end }}
            {{- if $lcCType }}
              lcCType: {{ $lcCType }}
            {{- end }}
            {{- if $lcCollate }}
              lcCollate: {{ $lcCollate }}
            {{- end }}
            {{- if $template }}
              template: {{ $template }}
            {{- end }}
            providerConfigRef:
              kind: ProviderConfig
              name: {{ .observed.composite.resource.spec.instanceRef.name }}-providerconfig
          {{- range $index, $extension := .observed.composite.resource.spec.extensions }}
          ---
          apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
          kind: Extension
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: extension-{{ $extension.name }}-{{ $index }}
            name: {{ $.observed.composite.resource.metadata.name }}-{{ $extension.name }}
            namespace: {{ $.observed.composite.resource.metadata.namespace }}
          spec:
            forProvider:
              extension: {{ $extension.name }}
              database: {{ $.observed.composite.resource.metadata.name }}
            {{- if $extension.schema }}
              schema: {{ $extension.schema }}
            {{- end }}
            providerConfigRef:
              kind: ProviderConfig
              name: {{ $.observed.composite.resource.spec.instanceRef.name }}-providerconfig
          {{- end }}
  - step: protect-grant-until-database-deleted
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          apiVersion: protection.crossplane.io/v1beta1
          kind: Usage
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: grant-usage
            name: {{ .observed.composite.resource.metadata.name }}-grant-usage
            namespace: {{ .observed.composite.resource.metadata.namespace }}
          spec:
            replayDeletion: true
            of:
              apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
              kind: Grant
              resourceRef:
                name: {{ .observed.composite.resource.metadata.name }}-grant-owner-to-dbadmin
            by:
              apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
              kind: Database
              resourceRef:
                name: {{ .observed.composite.resource.metadata.name }}
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready