apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresqldatabases.database.entigo.com
spec:
  compositeTypeRef:
    apiVersion: database.entigo.com/v1alpha1
    kind: PostgreSQLDatabase
  mode: Pipeline
  pipeline:
    - step: postgresqldatabase
      functionRef:
        name: platform-apis-database-fn