apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: postgresqldatabases.database.entigo.com
spec:
  defaultCompositeDeletePolicy: Foreground
  scope: Namespaced
  group: database.entigo.com
  names:
    kind: PostgreSQLDatabase
    plural: postgresqldatabases
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                owner:
                  description: Owner role name
                  type: string
                encoding:
                  description: Character set encoding to use in the new database. Specify a string constant (e.g., 'SQL_ASCII'), or an integer encoding number, or DEFAULT to use the default encoding (namely, the encoding of the template database).
                  type: string
                lcCType:
                  description: Character classification (LC_CTYPE) to use in the new database. This affects the categorization of characters, e.g. lower, upper and digit. The default is to use the character classification of the template database.
                  type: string
                lcCollate:
                  description: Collation order (LC_COLLATE) to use in the new database. This affects the sort order applied to strings, e.g. in queries with ORDER BY, as well as the order used in indexes on text columns. The default is to use the collation order of the template database.
                  type: string
                dbTemplate:
                  description: The name of the template from which to create the new database
                  type: string
                instanceRef:
                  type: object
                  properties:
                    name:
                      description: Name of the database instance the db should be created in
                      type: string
                  required:
                    - name
                extensions:
                  description: List of PostgreSQL extensions to enable
                  type: array
                  items:
                    type: string
                    enum:
                      - postgis
              required:
                - owner
                - instanceRef
