apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresqlusers.database.entigo.com
spec:
  compositeTypeRef:
    apiVersion: database.entigo.com/v1alpha1
    kind: PostgreSQLUser
  mode: Pipeline
  pipeline:
  - step: role
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- $roleExists := hasKey .observed.resources "role" -}}
          {{- $ready := $roleExists -}}
          {{- if not $ready -}}
          {{- $instances := getExtraResources . "postgresql-instance" -}}
          {{- if $instances -}}
          {{- $instance := mustFirst $instances -}}
          {{- range $instance.resource.status.conditions -}}
          {{- if and (eq .type "Ready") (eq .status "True") -}}{{- $ready = true -}}{{- end -}}
          {{- end -}}
          {{- end -}}
          {{- if not $ready }}
          apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
          kind: ExtraResources
          requirements:
            postgresql-instance:
              apiVersion: database.entigo.com/v1alpha1
              kind: PostgreSQLInstance
              matchName: {{ .observed.composite.resource.spec.instanceRef.name }}
          {{- end -}}
          {{- end -}}
          {{- if $ready }}
          ---
          apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
          kind: Role
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: role
              crossplane.io/external-name: "{{- if .observed.composite.resource.spec.name -}}{{- .observed.composite.resource.spec.name -}}{{- else -}}{{- .observed.composite.resource.metadata.name -}}{{- end -}}"
            name: {{ .observed.composite.resource.metadata.name }}
            namespace: {{ .observed.composite.resource.metadata.namespace }}
          spec:
            writeConnectionSecretToRef:
              name: {{ .observed.composite.resource.spec.instanceRef.name }}-{{ .observed.composite.resource.metadata.name }}
            forProvider:
              privileges:
                createDb: {{ .observed.composite.resource.spec.createDb }}
                login: {{ .observed.composite.resource.spec.login }}
                createRole: {{ .observed.composite.resource.spec.createRole }}
                inherit: {{ .observed.composite.resource.spec.inherit }}
            providerConfigRef:
              kind: ProviderConfig
              name: {{ .observed.composite.resource.spec.instanceRef.name }}-providerconfig
          {{- end }}
  - step: grants
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{ if .observed.composite.resource.spec.grant }}
            {{ range $roleName := .observed.composite.resource.spec.grant.roles }}
          ---
          apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
          kind: Grant
          metadata:
            name: grant-{{ $.observed.composite.resource.metadata.name }}-{{ $roleName | replace "_" "-" }}-{{ $.observed.composite.resource.spec.instanceRef.name }}
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: grant-{{ $.observed.composite.resource.metadata.name }}-{{ $roleName | replace "_" "-" }}-{{ $.observed.composite.resource.spec.instanceRef.name }}
          spec:
            forProvider:
              role: "{{- if $.observed.composite.resource.spec.name -}}{{- $.observed.composite.resource.spec.name -}}{{- else -}}{{- $.observed.composite.resource.metadata.name -}}{{- end -}}"
              memberOf: {{ $roleName }}
            providerConfigRef:
              kind: ProviderConfig
              name: {{ $.observed.composite.resource.spec.instanceRef.name }}-providerconfig
            {{ end }}
          {{ end }}
  - step: usages
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{ if .observed.composite.resource.spec.grant }}
            {{ range $roleName := .observed.composite.resource.spec.grant.roles }}
          ---
          apiVersion: protection.crossplane.io/v1beta1
          kind: Usage
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: usage-grant-{{ $.observed.composite.resource.metadata.name }}-{{ $roleName | replace "_" "-" }}-{{ $.observed.composite.resource.spec.instanceRef.name }}
            name: usage-grant-{{ $.observed.composite.resource.metadata.name }}-{{ $roleName | replace "_" "-" }}-{{ $.observed.composite.resource.spec.instanceRef.name }}
            namespace: {{ $.observed.composite.resource.metadata.namespace }}
          spec:
            replayDeletion: true
            of:
              apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
              kind: Role
              resourceRef:
                name: {{ $.observed.composite.resource.metadata.name }}
            by:
              apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
              kind: Grant
              resourceRef:
                name: grant-{{ $.observed.composite.resource.metadata.name }}-{{ $roleName | replace "_" "-" }}-{{ $.observed.composite.resource.spec.instanceRef.name }}
            {{ end }}
          {{ end }}
  - step: protect-instance-until-user-deleted
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          apiVersion: protection.crossplane.io/v1beta1
          kind: Usage
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: instance-protection
            name: {{ .observed.composite.resource.metadata.name }}-instance-protection
            namespace: {{ .observed.composite.resource.metadata.namespace }}
          spec:
            replayDeletion: true
            of:
              apiVersion: database.entigo.com/v1alpha1
              kind: PostgreSQLInstance
              resourceRef:
                name: {{ .observed.composite.resource.spec.instanceRef.name }}
            by:
              apiVersion: database.entigo.com/v1alpha1
              kind: PostgreSQLUser
              resourceRef:
                name: {{ .observed.composite.resource.metadata.name }}
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready
  - step: sequence-creation
    functionRef:
      name: function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      rules:
        - sequence:
          - role
          - grant-.*
          - usage-grant-.*
          - instance-protection
