apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresqlusers.database.entigo.com
spec:
  compositeTypeRef:
    apiVersion: database.entigo.com/v1alpha1
    kind: PostgreSQLUser
  mode: Pipeline
  pipeline:
    - step: postgresqluser
      functionRef:
        name: platform-apis-database-fn



