apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: repository-example-environment
data:
  awsProvider: crossplane-aws
  awsRegion: eu-west-1
  dataKMSKey: data
# scanOnPush: bool
# imageTagMutability: string