apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: platform-apis-artifact
data:
  awsProvider: crossplane-aws
  awsRegion: eu-north-1
  dataKMSKey: data
# scanOnPush: bool
# imageTagMutability: string