apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: eks
status:
  atProvider:
    arn: arn:aws:eks:eu-north-1:012345678901:cluster/eks
    region: eu-north-1
    identity:
      - oidc:
          - issuer: https://oidc.eks.eu-north-1.amazonaws.com/id/EXAMPLE123
  conditions:
    - lastTransitionTime: "2025-01-01T00:00:00Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2025-01-01T00:00:00Z"
      reason: Available
      status: "True"
      type: Ready
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Alias
metadata:
  name: data
status:
  atProvider:
    targetKeyArn: arn:aws:kms:eu-north-1:012345678901:key/mrk-0
    arn: arn:aws:kms:eu-north-1:012345678901:alias/data
    id: alias/data
  conditions:
    - lastTransitionTime: "2025-01-01T00:00:00Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2025-01-01T00:00:00Z"
      reason: Available
      status: "True"
      type: Ready
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Alias
metadata:
  name: config
status:
  atProvider:
    targetKeyArn: arn:aws:kms:eu-north-1:012345678901:key/mrk-1
    arn: arn:aws:kms:eu-north-1:012345678901:alias/config
    id: alias/config
  conditions:
    - lastTransitionTime: "2025-01-01T00:00:00Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2025-01-01T00:00:00Z"
      reason: Available
      status: "True"
      type: Ready
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    tenancy.entigo.com/zone: dev
