apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: eks
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  managementPolicies:
  - Observe
  providerConfigRef:
    kind: ClusterProviderConfig
    name: crossplane-aws
status:
  atProvider:
    arn: arn:aws:eks:eu-north-1:012345678901:cluster/eks
    region: eu-north-1
    identity:
      - oidc:
          - issuer: https://oidc.eks.eu-north-1.amazonaws.com/id/EXAMPLE123

---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Alias
metadata:
  name: data
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  initProvider: {}
  managementPolicies:
  - Observe
  providerConfigRef:
    kind: ClusterProviderConfig
    name: crossplane-aws
status:
  atProvider:
    arn: arn:aws:kms:eu-north-1:012345678901:alias/data
    id: alias/data
    region: eu-north-1
    targetKeyArn: arn:aws:kms:eu-north-1:012345678901:key/mrk-0

---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Alias
metadata:
  name: config
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  initProvider: {}
  managementPolicies:
  - Observe
  providerConfigRef:
    kind: ClusterProviderConfig
    name: crossplane-aws
status:
  atProvider:
    arn: arn:aws:kms:eu-north-1:012345678901:alias/config
    id: alias/config
    region: eu-north-1
    targetKeyArn: arn:aws:kms:eu-north-1:012345678901:key/mrk-1

---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    tenancy.entigo.com/zone: dev
