apiVersion: eks.aws.m.upbound.io/v1beta1
kind: Cluster
metadata:
  name: eks
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  managementPolicies:
  - Observe
  providerConfigRef:
    name: crossplane-aws
status:
  atProvider:
    arn: arn:aws:eks:eu-north-1:012345678901:cluster/eks
    region: eu-north-1
    identity:
      - oidc:
          - issuer: https://oidc.eks.eu-north-1.amazonaws.com/id/EXAMPLE123

---
apiVersion: kms.aws.m.upbound.io/v1beta1
kind: Key
metadata:
  name: data
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  managementPolicies:
  - Observe
  providerConfigRef:
    name: crossplane-aws
status:
  atProvider:
    arn: arn:aws:kms:eu-north-1:012345678901:key/mrk-0
    region: eu-north-1

---
apiVersion: kms.aws.m.upbound.io/v1beta1
kind: Key
metadata:
  name: config
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
  managementPolicies:
  - Observe
  providerConfigRef:
    name: crossplane-aws
status:
  atProvider:
    arn: arn:aws:kms:eu-north-1:012345678901:key/mrk-1
    region: eu-north-1

---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    tenancy.entigo.com/zone: dev
