apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rabbitmqbrokers.mq.entigo.com
spec:
  compositeTypeRef:
    apiVersion: mq.entigo.com/v1alpha1
    kind: RabbitMQBroker
  mode: Pipeline
  pipeline:
    - step: rabbitmqbroker
      functionRef:
        name: platform-apis-mq-fn



