postgresql:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-postgresql
    tag: v0.0.0
  function:
    image: ghcr.io/entigolabs/platform-apis-postgresql-fn
    tag: v0.0.0
    deploymentRuntimeConfig:
      awsProvider: "crossplane-aws"

repository:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-repository
    tag: v0.0.0
  function:
    image: ghcr.io/entigolabs/platform-apis-repository-fn
    tag: v0.0.0
  environmentConfig:
    awsProvider: "crossplane-aws"
    awsRegion: ""
    dataKMSKey: data
    scanOnPush: true
    imageTagMutability: "MUTABLE"

zone:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-zone
    tag: v0.0.0
  environmentConfig:
    argoCDNamespace: "argocd"
    awsProvider: "crossplane-aws"
    appProject:
      maintainerGroups: []
      observerGroups: []

webaccess:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-webaccess
    tag: v0.0.0

webapp:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-webapp
    tag: v0.0.0

cronjob:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-cronjob
    tag: v0.0.0

#Will be split later
developer-portal-function:
  install: true
  function:
    image: docker.io/entigolabs/developer-portal-function
    tag: v0.0.0-20251008090721-c7815a3bc8fa
    deploymentRuntimeConfig:
      awsProvider: "crossplane-aws"

providers: {}

functions:
 function-go-templating:
   install: true
   image: xpkg.upbound.io/crossplane-contrib/function-go-templating
   tag: v0.11.0
 function-auto-ready:
   install: true
   image: xpkg.upbound.io/crossplane-contrib/function-auto-ready
   tag: v0.5.0
 function-sequencer:
   install: true
   image: xpkg.upbound.io/crossplane-contrib/function-sequencer
   tag: v0.3.0


extraFunctions: []
#  - name: function-foo
#    image: xpkg.upbound.io/crossplane-contrib/function-foo
#    tag: v0.1.0
extraProviders: []
#  - name: provider-bar
#    image: xpkg.upbound.io/upbound/provider-bar
#    tag: v0.1.0
