database:
  function:
    image: ghcr.io/entigolabs/platform-apis-database-fn
    tag: v0.0.0
  environmentConfig:
    awsProvider: crossplane-aws
    dataKMSKey: data
    configKMSKey: config
    vpc: vpc
    subnetGroup: database

postgresql:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-postgresql
    tag: v0.0.0

artifact:
  function:
    image: ghcr.io/entigolabs/platform-apis-artifact-fn
    tag: v0.0.0
  environmentConfig:
    awsProvider: "crossplane-aws"
    awsRegion: ""
    dataKMSKey: data
    scanOnPush: true
    imageTagMutability: "MUTABLE"

repository:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-repository
    tag: v0.0.0

zone:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-zone
    tag: v0.0.0
  environmentConfig:
    argoCDNamespace: "argocd"
    awsProvider: "crossplane-aws"
    appProject:
      maintainerGroups: []
      observerGroups: []
  clusterrolebinding:
    maintainerGroups: ["maintainer"]
    observerGroups: ["observer"]
    contributorGroups: ["contributor"]

networking:
  function:
    image: ghcr.io/entigolabs/platform-apis-networking-fn
    tag: v0.0.0
  environmentConfig:
    istioGateway: "istio-gateway/istio-gateway"

webaccess:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-webaccess
    tag: v0.0.0

workload:
  function:
    image: ghcr.io/entigolabs/platform-apis-workload-fn
    tag: v0.0.0
  environmentConfig:
    cpuRequestMultiplier: 0.5
    memoryRequestMultiplier: 0.8
    imagePullSecrets: []

webapp:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-webapp
    tag: v0.0.0

cronjob:
  install: true
  package:
    image: ghcr.io/entigolabs/platform-apis-cronjob
    tag: v0.0.0

providers: {}

functions:
 function-go-templating:
   install: true
   image: xpkg.upbound.io/crossplane-contrib/function-go-templating
   tag: v0.11.0
 function-auto-ready:
   install: true
   image: xpkg.upbound.io/crossplane-contrib/function-auto-ready
   tag: v0.5.0
 function-sequencer:
   install: true
   image: xpkg.upbound.io/crossplane-contrib/function-sequencer
   tag: v0.3.0


extraFunctions: []
#  - name: function-foo
#    image: xpkg.upbound.io/crossplane-contrib/function-foo
#    tag: v0.1.0
extraProviders: []
#  - name: provider-bar
#    image: xpkg.upbound.io/upbound/provider-bar
#    tag: v0.1.0
