# Example ValkeyInstance
apiVersion: database.entigo.com/v1alpha1
kind: ValkeyInstance
metadata:
  name: example-valkey
spec: {}

---
# Example ValkeyInstance with deletion protection disabled
apiVersion: database.entigo.com/v1alpha1
kind: ValkeyInstance
metadata:
  name: example-valkey-no-deletion-protection
spec:
  deletionProtection: false

---
# Example ValkeyInstance with custom settings
apiVersion: database.entigo.com/v1alpha1
kind: ValkeyInstance
metadata:
  name: example-valkey-with-custom-settings
spec:
  deletionProtection: true
  engineVersion: "8.2"
  instanceType: "cache.t4g.small"
  numCacheClusters: 3
  autoMinorVersionUpgrade: true
  maintenanceWindow: "mon:00:00-mon:03:00"
  snapshotWindow: "05:00-06:00"
  snapshotRetentionLimit: 10
  parameterGroupName: "default.valkey8"
