apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  name: vpc
  namespace: crossplane-aws
spec:
  forProvider:
    region: eu-north-1
status:
  atProvider:
    id: vpc-1234567890abcdef0
---
apiVersion: elasticache.aws.m.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  name: elasticache
  namespace: crossplane-aws
status:
  atProvider:
    id: my-elasticache-subnet-group
---
apiVersion: kms.aws.m.upbound.io/v1beta1
kind: Key
metadata:
  name: data
  namespace: crossplane-aws
status:
  atProvider:
    arn: arn:aws:kms:eu-north-1:123456789012:key/data-key-uuid
---
apiVersion: kms.aws.m.upbound.io/v1beta1
kind: Key
metadata:
  name: config
  namespace: crossplane-aws
status:
  atProvider:
    arn: arn:aws:kms:eu-north-1:123456789012:key/config-key-uuid
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: compute-subnet
  namespace: crossplane-aws
  labels:
    subnet-type: compute
status:
  atProvider:
    cidrBlock: 10.0.1.0/24
    id: subnet-12345
