apiVersion: workload.entigo.com/v1alpha1
kind: WebApp
metadata:
  name: new-web-app
spec:
  replicas: 1
  restartPolicy: "Always"
  containers:
    - name: nginx
      registry: 1234567890.dkr.ecr.eu-north-1.amazonaws.com
      repository: nginx
      tag: mainline-alpine-slim
      resources:
        limits:
          cpu: 0.25
          ram: 128
      services:
        - name: http-tcp-80
          port: 80
          protocol: "TCP"
        - name: http-tcp-443
          port: 443
          protocol: "TCP"
