name: Build PostgreSQL Composition

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'compositions/postgresql/**'
  pull_request:
    paths:
      - 'compositions/postgresql/**'
    
jobs:
  build:
    uses: ./.github/workflows/builder-composition.yml
    with:
      path: compositions/postgresql
      name: platform-apis-postgresql
    secrets: inherit
