name: Build S3Bucket Composition

on:
  workflow_dispatch:
#  push:
#    branches: [main]
#    paths:
#      - "compositions/s3bucket/**"
#      - '!compositions/s3bucket/examples/**'
#  pull_request:
#    paths:
#      - "compositions/s3bucket/**"
#      - '!compositions/s3bucket/examples/**'

jobs:
  build:
    uses: ./.github/workflows/builder-composition.yml
    with:
      path: compositions/s3bucket
      name: platform-apis-s3bucket
    secrets: inherit
