name: Build Webapp Composition

on:
  workflow_dispatch:
#  push:
#    branches: [main]
#    paths:
#      - 'compositions/webapp/**'
#  pull_request:
#    paths:
#      - 'compositions/webapp/**'
    
jobs:
  build:
    uses: ./.github/workflows/builder-composition.yml
    with:
      path: compositions/webapp
      name: platform-apis-webapp
    secrets: inherit
