name: Build Repository Composition

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'compositions/repository/**'
      - '!compositions/repository/examples/**'
  pull_request:
    paths:
      - 'compositions/repository/**'
      - '!compositions/repository/examples/**'
    
jobs:
  build:
    uses: ./.github/workflows/builder-composition.yml
    with:
      path: compositions/repository
      name: platform-apis-repository
    secrets: inherit
