name: Build Valkey Composition

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "compositions/valkey/**"
  pull_request:
    paths:
      - "compositions/valkey/**"

jobs:
  build:
    uses: ./.github/workflows/builder-composition.yml
    with:
      path: compositions/valkey
      name: platform-apis-valkey
    secrets: inherit
