name: Build Networking Function

on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'functions/networking/**'
#      - 'functions/common/base/**'
#  pull_request:
#    paths:
#      - 'functions/networking/**'
#      - 'functions/common/base/**'
  workflow_dispatch:
    inputs:
      version:
        description: Package version (e.g. v0.1.0)
        required: false

jobs:
  build:
    uses: ./.github/workflows/builder-function.yml
    with:
      path: functions/networking
      name: platform-apis-networking-fn
      version: ${{ inputs.version }}
    secrets: inherit