name: Build Database Function

on:
  push:
    branches:
      - main
    paths:
      - 'functions/database/**'
      - 'functions/common/base/**'
  pull_request:
    paths:
      - 'functions/database/**'
      - 'functions/common/base/**'
  workflow_dispatch:
    inputs:
      version:
        description: Package version (e.g. v0.1.0)
        required: false

jobs:
  build:
    uses: ./.github/workflows/builder-function.yml
    with:
      path: functions/database
      name: platform-apis-database-fn
      version: ${{ inputs.version }}
    secrets: inherit
