name: Execute Infralib Tests

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Infralib branch to test"
        required: true
        type: string
      helm_version:
        description: "Helm version (for reporting only)"
        required: true
        type: string

env:
  INFRALIB_REPO: entigolabs/entigo-infralib
  INFRALIB_MODULE_PATH: modules/k8s/platform-apis

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    concurrency:
      group: infralib-e2e-tests
      cancel-in-progress: false
    steps:
      - name: Checkout entigo-infralib
        uses: actions/checkout@v4
        with:
          repository: ${{ env.INFRALIB_REPO }}
          token: ${{ secrets.INFRALIB_PAT }}
          ref: ${{ inputs.branch_name }}
          path: infralib

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Test Script
        id: tests
        working-directory: infralib/${{ env.INFRALIB_MODULE_PATH }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          set +e
          ./test.sh
