name: Test compositions

on:
  workflow_call:
    inputs:
      compositions:
        description: 'JSON array of compositions to test'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    #runs-on: arc-runner-set
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        composition: ${{ fromJson(inputs.compositions) }}
    name: Test ${{ matrix.composition }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run tests
        env:
          GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        run: ./run-tests.sh compositions/${{ matrix.composition }}
