apiVersion: mq.entigo.com/v1alpha1
kind: RabbitMQBroker
metadata:
  name: rabbitmq-example
spec:
  instanceType: mq.m7g.medium
  engineVersion: "4.2"
  engineType: RabbitMQ
  deploymentMode: SINGLE_INSTANCE
  publiclyAccessible: false